feat: enable time zone support
ietf-tools/mailarch pull request #3626
Opened 2023-07-12 22:08 UTC by rpcross

In preparation for migration to Postgres enable time zone support. USE_TZ = True.

2023-07-23 17:45 UTC, jennifer-richards requested changes
See inline. Also, are the `msg.mbox` and `msg.txt` files used anywhere? I could not find a reference to them.

I think you'll also need to convert times in the database from `America/Los_Angeles` to UTC - are you planning a migration for that or do you have another plan in mind to rebuild those?

2023-07-23 17:45 UTC, jennifer-richards commented on backend/mlarchive/archive/mail.py
> +                    return date.replace(tzinfo=ZoneInfo('UTC'))
I think you've elsewhere used `datetime.timezone.utc` as your utc tzinfo. That's what we did in datatracker, and I think it's the best choice, but I think it's definitely better to be consistent. Otherwise problems with comparisons are more likely to arise.

2023-07-24 18:48 UTC, rpcross commented on backend/mlarchive/archive/mail.py
> +                    return date.replace(tzinfo=ZoneInfo('UTC'))
Despite TIME_ZONE setting changing from 'America/Los_Angeles' to 'UTC', USE_TZ was False and all message times in the database are UTC time, so no migrations are necessary.

2023-07-25 00:50 UTC, jennifer-richards commented on backend/mlarchive/archive/mail.py
> +                    return date.replace(tzinfo=ZoneInfo('UTC'))
> Despite TIME_ZONE setting changing from 'America/Los_Angeles' to 'UTC', USE_TZ was False and all message times in the database are UTC time, so no migrations are necessary.

Did you check / do you care about the `updated` fields on some of the models? At least some are `auto_now`, which I think means they'll have used `TIME_ZONE`.

2023-09-15 17:01 UTC, rpcross commented on backend/mlarchive/archive/mail.py
> +                    return date.replace(tzinfo=ZoneInfo('UTC'))
The updated fields currently contain Pacific times, after this release they will be seen as UTC times, but this is inconsequential. They aren't really used right now. I plan to change update_index to use Message.updated but that should only affect future messages, which will have correct updated values going forward.

2023-09-18 17:57 UTC, jennifer-richards approved these changes

2023-09-18 21:45 UTC, merged